### PR TITLE
BaSP-TG-90: Employee functionalities

### PR DESCRIPTION
**Pull request by DinoStampella**

### CODE REVIEW

**Review by JulianFloresDev — DISMISSED** [review]
I'm agree with this changes!!! Well done!!

**Review by kolodani — DISMISSED** [review]
Great work

**Review by JulianFloresDev — APPROVED** [review]
Diss miss prev apprrove!! This is de one, with fixed errors!!

**Review by kolodani — APPROVED** [review]
Good Job !!!

**Review by agusgatto8 — APPROVED** [review]

**Pull request merged**
