### PR TITLE
BaSP-TG-54: Resolve Employee Features

### PR DESCRIPTION
**Pull request by JulianFloresDev**
**In an attempt to resume everything that has been done, we will describe the points that were worked on and the functionalities afterwards:**

- > Implement of `react-hook-form` librarie. (TG-54)
- > Refactor **Share** components **folder** with an **index.jsx** whichs contains all other components import inside & unique **export** (TG-55)
- > Create Employee Features to render the tables corresponding to the actions that an employee is allowed to perform in the app (TG-56)
- > Create Log In button and feature un Home Component.

image
image

### CODE REVIEW

**Review by kolodani — DISMISSED** [review]
Nice Work !!!

**Review by kolodani — DISMISSED** [review]
great job !!!

**Review by LuisQueff — CHANGES_REQUESTED** [review]
`export const userValidation = Joi.object({
  email: Joi.string()
    .email({ tlds: { allow: false } })
    .required()
    .messages({
      'string.empty': 'Email is required',
      'string.required': 'Email is required',
      'string.email': 'Email must be a falid email format'
    }),`

Please check this small typo (Email must be a falid email format)

**Review by kolodani — APPROVED** [review]
well done !!!

**Review by LuisQueff — APPROVED** [review]

**Pull request merged**
